export const guides = [
  {
    id: 'dilnoza-kamilova',
    slug: 'dilnoza-kamilova',
    name: 'Dilnoza Kamilova',
    photo: { src: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&q=85&w=900', alt: 'Dilnoza Kamilova, local guide' },
    city: 'Samarkand',
    regions: ['Samarkand', 'Bukhara'],
    languages: ['English', 'Russian', 'Uzbek'],
    specializations: ['History', 'Food tours'],
    pricing: { currency: 'USD', perDay: 95, perHour: 15 },
    rating: 4.9,
    reviewCount: 28,
    bio: 'Historian and food lover who makes Silk Road stories feel personal and memorable.',
    description: 'Leads small private groups through Samarkand and Bukhara, mixing landmark visits with local workshops and teahouses.',
    portfolio: [],
    reviews: [],
    availableDates: ['2026-08-04', '2026-08-06', '2026-08-09'],
    contact: { telegramUsername: 'dilnoza_guide', shareAfterRequestApproval: true }
  },
  {
    id: 'aziz-tashkent',
    slug: 'aziz-tashkent',
    name: 'Aziz Karimov',
    photo: { src: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=85&w=900', alt: 'Aziz Karimov, guide in Tashkent' },
    city: 'Tashkent',
    regions: ['Tashkent'],
    languages: ['Russian', 'Uzbek'],
    specializations: ['City walks', 'Architecture'],
    pricing: { currency: 'USD', perDay: 80, perHour: 12 },
    rating: 4.7,
    reviewCount: 14,
    bio: 'Local urbanist who knows Tashkent’s neighborhoods, markets and modern architecture.',
    description: 'Custom city walks focused on architecture, parks and contemporary food spots.',
    portfolio: [],
    reviews: [],
    availableDates: ['2026-07-25', '2026-07-28'],
    contact: { telegramUsername: 'aziz_tash', shareAfterRequestApproval: true }
  },
  {
    id: 'mariya-bukhara',
    slug: 'mariya-bukhara',
    name: 'Mariya Sokolova',
    photo: { src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4ebzEpOco1zaiBDiDpb2lzjCFu_a8yE_P0SxpUuRA_w3AlZWDSLR89rqp&s=10', alt: 'Mariya Sokolova, guide in Bukhara' },
    city: 'Bukhara',
    regions: ['Bukhara'],
    languages: ['English', 'Russian'],
    specializations: ['History', 'Museums'],
    pricing: { currency: 'USD', perDay: 70, perHour: 10 },
    rating: 4.8,
    reviewCount: 20,
    bio: 'Expert in Bukhara’s monuments and storytelling tours.',
    description: 'Tours through historic madrasas, baths and bazaars with local context and anecdotes.',
    portfolio: [],
    reviews: [],
    availableDates: ['2026-08-01', '2026-08-10'],
    contact: { telegramUsername: 'mariya_bux', shareAfterRequestApproval: false }
  },
  {
    id: 'omid-khiva',
    slug: 'omid-khiva',
    name: 'Omid Rahmon',
    photo: { src: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=85&w=900', alt: 'Omid Rahmon, guide in Khiva' },
    city: 'Khiva',
    regions: ['Khiva'],
    languages: ['Uzbek', 'Russian'],
    specializations: ['Heritage', 'Photography tours'],
    pricing: { currency: 'USD', perDay: 60, perHour: 9 },
    rating: 4.6,
    reviewCount: 8,
    bio: 'Local photographer and guide who frames Khiva beautifully.',
    description: 'Photo-friendly walking routes and visits to old medressas at golden hour.',
    portfolio: [],
    reviews: [],
    availableDates: ['2026-07-30', '2026-08-05'],
    contact: { telegramUsername: 'omid_khiva', shareAfterRequestApproval: true }
  },
  {
    id: 'nurmukhammed-nukus',
    slug: 'nurmukhammed-nukus',
    name: 'Nurmukhammed T.',
    photo: { src: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?auto=format&fit=crop&q=85&w=900', alt: 'Guide in Nukus' },
    city: 'Nukus',
    regions: ['Nukus'],
    languages: ['Russian'],
    specializations: ['Modern art', 'Museums'],
    pricing: { currency: 'USD', perDay: 50, perHour: 8 },
    rating: 4.5,
    reviewCount: 5,
    bio: 'Knowledgeable about the Nukus Museum and regional modern art.',
    description: 'Guided tours of Savitsky Museum and local galleries.',
    portfolio: [],
    reviews: [],
    availableDates: ['2026-08-12', '2026-08-15'],
    contact: { telegramUsername: 'nurmuk_nk', shareAfterRequestApproval: false }
  },
  {
    id: 'laylo-namangan',
    slug: 'laylo-namangan',
    name: 'Laylo Ismailova',
    photo: { src: 'https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?auto=format&fit=crop&q=85&w=900', alt: 'Laylo Ismailova, guide' },
    city: 'Namangan',
    regions: ['Namangan'],
    languages: ['Uzbek', 'Russian'],
    specializations: ['Nature', 'Hiking'],
    pricing: { currency: 'USD', perDay: 65, perHour: 10 },
    rating: 4.8,
    reviewCount: 12,
    bio: 'Hiking guide for the Fergana valley and nearby mountains.',
    description: 'Day trips and multi-day hikes with local food stops.',
    portfolio: [],
    reviews: [],
    availableDates: ['2026-09-01', '2026-09-10'],
    contact: { telegramUsername: 'laylo_hikes', shareAfterRequestApproval: true }
  },
  {
    id: 'bek-fergana',
    slug: 'bek-fergana',
    name: 'Bek Rasulov',
    photo: { src: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=85&w=900', alt: 'Bek Rasulov, guide' },
    city: 'Fergana',
    regions: ['Fergana'],
    languages: ['Uzbek', 'English'],
    specializations: ['Crafts', 'Markets'],
    pricing: { currency: 'USD', perDay: 55, perHour: 9 },
    rating: 4.4,
    reviewCount: 7,
    bio: 'Market expert and craft workshop host.',
    description: 'Visits to silk workshops, pottery and local bazaars.',
    portfolio: [],
    reviews: [],
    availableDates: ['2026-08-20', '2026-08-22'],
    contact: { telegramUsername: 'bek_ferg', shareAfterRequestApproval: false }
  },
  {
    id: 'ali-andijan',
    slug: 'ali-andijan',
    name: 'Ali Mirzo',
    photo: { src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQf0TsOl6fnLfEddas8Wd_Sm24Yp5348BMKpDtlE9MZ74XnkN2B9c_3I2f&s=10', alt: 'Ali Mirzo, guide' },
    city: 'Andijan',
    regions: ['Andijan'],
    languages: ['Russian', 'Uzbek', 'English'],
    specializations: ['Culture', 'Family tours'],
    pricing: { currency: 'USD', perDay: 45, perHour: 7 },
    rating: 4.3,
    reviewCount: 4,
    bio: 'Friendly local guide for family-friendly tours and cultural visits.',
    description: 'Small group tours suitable for families and slower-paced visits.',
    portfolio: [],
    reviews: [],
    availableDates: ['2026-07-26', '2026-07-29'],
    contact: { telegramUsername: 'ali_guide', shareAfterRequestApproval: true }
  }
];
