(() => {
    const STORE = { user: 'uzexplore-user', bookings: 'uzexplore-bookings' };
    const destinations = {
        tashkent: { name:'Ташкент', region:'город Ташкент', tagline:'Современная столица среди зелёных парков и восточных базаров', season:'апрель–май и сентябрь–октябрь', days:'2–3 дня', center:'41.3111, 69.2797', about:'Ташкент соединяет советский модернизм, исламское наследие, метро, гастрономию и спокойные зелёные кварталы.', places:[['Комплекс Хаст-Имам','41.3370, 69.2404','Духовный центр с медресе Баракхан и библиотекой восточных рукописей.'],['Базар Чорсу','41.3265, 69.2357','Главный крытый рынок столицы: специи, лепёшки, сухофрукты и ремесленные товары.'],['Музей прикладного искусства','41.3054, 69.2575','Узбекская керамика, ткани, резьба и ювелирное искусство в историческом особняке.'],['Парк Навои','41.3043, 69.2452','Просторный городской парк для прогулок у каналов и культурных площадок.']] },
        samarkand: { name:'Самарканд', region:'Самаркандская область', tagline:'Голубые купола и сердце Великого шёлкового пути', season:'март–май и сентябрь–ноябрь', days:'2–3 дня', center:'39.6542, 66.9597', about:'Самарканд — монументальный город Тимуридов, где медресе, мавзолеи и живые рынки складываются в цельный исторический маршрут.', places:[['Площадь Регистан','39.6548, 66.9758','Ансамбль трёх медресе и главная архитектурная сцена города.'],['Шахи-Зинда','39.6628, 66.9875','Некрополь с выдающимися образцами майолики XI–XV веков.'],['Мавзолей Гур-Эмир','39.6485, 66.9685','Усыпальница Амира Темура под бирюзовым куполом.'],['Обсерватория Улугбека','39.6743, 66.9874','Остатки научного центра XV века и знаменитого секстанта.']] },
        bukhara: { name:'Бухара', region:'Бухарская область', tagline:'Живой музей караван-сараев, минаретов и тихих двориков', season:'март–май и сентябрь–ноябрь', days:'3 дня', center:'39.7681, 64.4556', about:'Старый город Бухары удобно исследовать пешком: большинство главных памятников, рынков и чайхан расположены рядом.', places:[['Пои-Калян','39.7759, 64.4147','Минарет Калян, мечеть и медресе Мири-Араб образуют главный ансамбль города.'],['Крепость Арк','39.7773, 64.4107','Древняя цитадель и резиденция бухарских эмиров.'],['Ляби-Хауз','39.7724, 64.4207','Историческая площадь у водоёма с медресе, чайханами и тутовыми деревьями.'],['Чор-Минор','39.7744, 64.4317','Камерное медресе с четырьмя бирюзовыми башнями.']] },
        khiva: { name:'Хива', region:'Хорезмская область', tagline:'Город-крепость из глины, бирюзы и вечернего света', season:'апрель–май и сентябрь–октябрь', days:'2 дня', center:'41.3775, 60.3619', about:'Исторический центр Хивы — компактный пешеходный город внутри крепостных стен, особенно красивый утром и на закате.', places:[['Ичан-Кала','41.3783, 60.3597','Охраняемый ЮНЕСКО внутренний город с дворцами, мечетями и минаретами.'],['Кальта-Минор','41.3780, 60.3591','Незавершённый бирюзовый минарет и символ Хивы.'],['Куня-Арк','41.3789, 60.3583','Цитадель хивинских ханов с тронным залом и смотровой площадкой.'],['Джума-мечеть','41.3774, 60.3614','Зал с сотнями резных деревянных колонн разных эпох.']] },
        nukus: { name:'Нукус', region:'Республика Каракалпакстан', tagline:'Авангардное искусство и ворота к истории Аральского моря', season:'апрель–май и сентябрь–октябрь', days:'2–3 дня', center:'42.4619, 59.6166', about:'Нукус — база для знакомства с каракалпакской культурой, уникальной коллекцией искусства и пустынными маршрутами.', places:[['Музей Савицкого','42.4648, 59.6078','Одна из крупнейших коллекций русского авангарда и каракалпакского искусства.'],['Каракалпакский краеведческий музей','42.4654, 59.6090','Археология, природа и этнография региона.'],['Муйнак и кладбище кораблей','43.7691, 59.0214','Однодневная экспедиция к бывшему берегу Аральского моря.'],['Некрополь Миздахкан','42.3965, 59.2806','Древний комплекс у Ходжейли с мавзолеями разных эпох.']] },
        andijan: { name:'Андижан', region:'Андижанская область', tagline:'Сады, базары и культурное сердце восточной Ферганской долины', season:'апрель–май и сентябрь', days:'1–2 дня', center:'40.7821, 72.3442', about:'Андижан знакомит с ремесленной и гастрономической культурой густонаселённой Ферганской долины.', places:[['Парк Бабура','40.7486, 72.3076','Мемориальный парк на холме, посвящённый поэту и основателю империи Великих Моголов.'],['Джами-комплекс','40.7834, 72.3432','Медресе, мечеть и минарет в историческом центре.'],['Базар Эски Шахар','40.7827, 72.3420','Традиционный рынок с фруктами, тканями и местной едой.'],['Музей Бабура','40.7831, 72.3448','Экспозиция о жизни и литературном наследии Захириддина Бабура.']] },
        namangan: { name:'Наманган', region:'Наманганская область', tagline:'Город цветов, духовных памятников и горных дорог', season:'апрель–июнь и сентябрь', days:'2 дня', center:'40.9983, 71.6726', about:'Наманган сочетает культурные памятники долины с удобными выездами в Чартак и предгорья.', places:[['Комплекс Мулла-Киргиз','41.0010, 71.6685','Медресе начала XX века с выразительной кирпичной кладкой.'],['Мавзолей Ходжамни-Кабри','41.0032, 71.6671','Почитаемый архитектурный комплекс в старой части города.'],['Парк Бабура','40.9994, 71.6755','Центральная зелёная зона города.'],['Чартак','41.0694, 71.8235','Курортное направление с минеральными источниками недалеко от города.']] },
        fergana: { name:'Фергана', region:'Ферганская область', tagline:'Шёлк, керамика и широкие зелёные улицы долины', season:'апрель–май и сентябрь–октябрь', days:'2–3 дня', center:'40.3894, 71.7870', about:'Фергана служит удобной базой для маршрутов в Маргилан, Риштан и Коканд.', places:[['Маргилан и фабрика Ёдгорлик','40.4711, 71.7247','Традиционное производство шёлка и ручного иката.'],['Риштанские мастерские','40.3561, 71.2847','Центр знаменитой голубой керамики Ферганской долины.'],['Краеведческий музей','40.3858, 71.7842','История, археология и природа области.'],['Центральный парк','40.3846, 71.7890','Тенистые аллеи в центре города.']] },
        jizzakh: { name:'Джизак', region:'Джизакская область', tagline:'Горные тропы, заповедники и ворота в Заамин', season:'апрель–июнь и сентябрь–октябрь', days:'2–3 дня', center:'40.1158, 67.8422', about:'Джизак — отправная точка для природных путешествий в Заамин и к северным склонам Туркестанского хребта.', places:[['Зааминский национальный парк','39.6094, 68.5154','Арчовые леса, горный воздух и пешеходные маршруты.'],['Санаторий Заамин','39.6580, 68.5360','Высокогорная курортная зона с панорамными дорогами.'],['Музей Хамида Алимджана','40.1169, 67.8441','Литературная и культурная история региона.'],['Айдаркуль','40.9184, 66.8556','Озеро и юртовые лагеря для отдельной поездки.']] },
        qarshi: { name:'Карши', region:'Кашкадарьинская область', tagline:'Южное наследие, древние мосты и дорога к Шахрисабзу', season:'март–май и сентябрь–ноябрь', days:'2 дня', center:'38.8610, 65.7847', about:'Карши — спокойный южный город с памятниками и удобным доступом к историческому Шахрисабзу.', places:[['Мост Амира Темура','38.8568, 65.7938','Исторический кирпичный мост через Кашкадарью.'],['Мечеть Кок-Гумбаз','38.8582, 65.7902','Архитектурный памятник с голубым куполом.'],['Медресе Одина','38.8601, 65.7891','Один из старейших сохранившихся памятников Карши.'],['Шахрисабз','39.0564, 66.8340','Родина Амира Темура и ансамбль дворца Ак-Сарай.']] },
        termez: { name:'Термез', region:'Сурхандарьинская область', tagline:'Буддийское наследие и самый солнечный юг страны', season:'март–апрель и октябрь–ноябрь', days:'2–3 дня', center:'37.2242, 67.2783', about:'Термез раскрывает малоизвестный пласт буддийской и эллинистической истории Центральной Азии.', places:[['Фаяз-Тепе','37.2867, 67.1889','Буддийский монастырский комплекс I–III веков.'],['Кара-Тепе','37.2850, 67.1840','Пещерный буддийский комплекс у Старого Термеза.'],['Султан-Саодат','37.2702, 67.3065','Ансамбль мавзолеев правителей Термеза.'],['Археологический музей','37.2298, 67.2735','Обширная коллекция находок Сурхандарьи.']] },
        gulistan: { name:'Гулистан', region:'Сырдарьинская область', tagline:'Спокойная остановка между Ташкентом и Самаркандом', season:'апрель–май и сентябрь–октябрь', days:'1 день', center:'40.4897, 68.7842', about:'Гулистан подойдёт для короткой остановки, знакомства с Сырдарьёй и локальной повседневной культурой.', places:[['Центральный парк','40.4907, 68.7862','Главная прогулочная зелёная зона города.'],['Краеведческий музей','40.4879, 68.7830','История освоения степи и культура области.'],['Набережная канала','40.4930, 68.7910','Спокойный городской маршрут у воды.'],['Сырдарья','40.8440, 68.6610','Природные виды и рыболовные места в области.']] },
        navoi: { name:'Навои', region:'Навоийская область', tagline:'Пустынные пейзажи, петроглифы и древний караванный путь', season:'март–май и сентябрь–ноябрь', days:'2–3 дня', center:'40.1039, 65.3688', about:'Навоийская область соединяет пустыню Кызылкум, горы Нуратау, древние петроглифы и ремесленные поселения.', places:[['Ущелье Сармышсай','40.3547, 65.6557','Крупнейшая галерея петроглифов региона среди скал и горных троп.'],['Нурата и источник Чашма','40.5617, 65.6882','Священный источник, мечеть и остатки крепости Александра Македонского.'],['Юртовый лагерь Айдаркуль','40.7420, 66.5730','Ночёвка в пустыне, верблюжьи прогулки и поездка к озеру.'],['Рабат-и Малик','40.1239, 65.1471','Монументальный портал караван-сарая XI века на старой дороге.']] },
        tashkent_region: { name:'Ташкентская область', region:'Ташкентская область', tagline:'Горы Западного Тянь-Шаня, водохранилища и курорты рядом со столицей', season:'май–октябрь, зимой — лыжи', days:'2–4 дня', center:'41.5700, 70.0200', about:'Область вокруг столицы — главное направление для горного отдыха: Чимган, Бельдерсай, Амирсой и Чарвак находятся в одном туристическом кластере.', places:[['Амирсой','41.4857, 69.9529','Всесезонный горный курорт с канатной дорогой и панорамными маршрутами.'],['Большой Чимган','41.5107, 70.0232','Треккинг, верховая езда и восхождения в Западном Тянь-Шане.'],['Чарвакское водохранилище','41.6250, 69.9960','Пляжи, водные активности и виды на горные хребты.'],['Петроглифы Ходжикента','41.6459, 69.9560','Древние наскальные изображения недалеко от Чарвака.']] }
    };

    const destinationPhotos = {
        tashkent:'https://commons.wikimedia.org/wiki/Special:FilePath/Tashkent%20City%20Park%20at%20night.jpg?width=1600',
        samarkand:'https://commons.wikimedia.org/wiki/Special:FilePath/Registan-Samarkand.jpg?width=1600',
        bukhara:'https://commons.wikimedia.org/wiki/Special:FilePath/View%20of%20Po-i-Kalyan.jpg?width=1600',
        khiva:'https://commons.wikimedia.org/wiki/Special:FilePath/Itchan%20Kala%20Khiva%202012.jpg?width=1600',
        nukus:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&q=85&w=1600',
        andijan:'https://commons.wikimedia.org/wiki/Special:FilePath/Devonaboy%20Jome%20Mosque%20in%20Andijan.jpg?width=1600',
        namangan:'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&q=85&w=1600',
        fergana:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&q=85&w=1600',
        jizzakh:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=85&w=1600',
        qarshi:'https://commons.wikimedia.org/wiki/Special:FilePath/Kok-Gumbaz%20mosque%20in%20Qarshi%2C%20view%20from%20the%20north-east.jpg?width=1600',
        termez:'https://commons.wikimedia.org/wiki/Special:FilePath/Termez%20Sultan-Saodat.jpg?width=1600',
        gulistan:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&q=85&w=1600',
        navoi:'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&q=85&w=1600',
        tashkent_region:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=85&w=1600'
    };
    const placePhotoQueries = {
        tashkent:['hazrati-imam-tashkent','chorsu-bazaar-tashkent','uzbek-art-museum','navoi-park-tashkent'],
        samarkand:['registan-samarkand','shah-i-zinda-samarkand','gur-e-amir-samarkand','ulugh-beg-observatory'],
        bukhara:['poi-kalyan-bukhara','ark-bukhara','lyabi-hauz-bukhara','chor-minor-bukhara'],
        khiva:['itchan-kala-khiva','kalta-minor-khiva','kunya-ark-khiva','juma-mosque-khiva'],
        nukus:['savitsky-museum-nukus','karakalpakstan-museum','muynak-aral-ships','mizdakhan-necropolis'],
        andijan:['babur-park-andijan','jami-mosque-andijan','uzbek-bazaar','babur-museum-andijan'],
        namangan:['mulla-kyrgyz-madrasa','namangan-mausoleum','namangan-park','chortoq-uzbekistan'],
        fergana:['margilan-silk','rishtan-ceramics','fergana-museum','fergana-park'],
        jizzakh:['zaamin-national-park','zaamin-mountains','jizzakh-uzbekistan','aydarkul-lake'],
        qarshi:['qarshi-bridge','kok-gumbaz-qarshi','qarshi-madrasa','ak-saray-shakhrisabz'],
        termez:['fayaz-tepe','kara-tepe-termez','sultan-saodat','termez-museum'],
        gulistan:['gulistan-uzbekistan','syrdarya-uzbekistan','uzbekistan-canal','syr-darya-river'],
        navoi:['sarmishsay-petroglyphs','nurata-chashma','aydarkul-yurt','rabat-malik'],
        tashkent_region:['amirsoy-mountains','chimgan-mountain','charvak-reservoir','khodjikent-petroglyphs']
    };
    const verifiedPlacePhotos = {
        samarkand: [
            'https://commons.wikimedia.org/wiki/Special:FilePath/Registan_Samarkand_Uzbekistan.JPG?width=1400',
            'https://commons.wikimedia.org/wiki/Special:FilePath/Shah-i-Zinda%2C_Samarkand_%288591680633%29.jpg?width=1400',
            'https://commons.wikimedia.org/wiki/Special:FilePath/Gur-Emir_Samarkand.jpg?width=1400',
            'https://commons.wikimedia.org/wiki/Special:FilePath/Ulugh_Beg_Observatory_01.jpg?width=1400'
        ]
    };
    const hotelPhotos = [
        'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=85&w=1200',
        'https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&q=85&w=1200',
        'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&q=85&w=1200'
    ];
    const placePhoto = (slug,index) => verifiedPlacePhotos[slug]?.[index] || destinationPhotos[slug];
    const hotelPhoto = (_slug,index) => hotelPhotos[index];

    const hotelNames = ['Silk Road Residence','Old City Boutique','UzExplore City Hotel'];
    const read = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) || fallback; } catch { return fallback; } };
    const write = (key, value) => localStorage.setItem(key, JSON.stringify(value));
    const user = () => read(STORE.user, null);
    const esc = value => String(value).replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
    const toast = message => { const el=document.createElement('div'); el.className='app-toast'; el.textContent=message; document.body.append(el); setTimeout(()=>el.classList.add('show'),20); setTimeout(()=>el.remove(),3200); };

    function modal(title, body) {
        document.querySelector('.app-modal')?.remove();
        const wrap=document.createElement('div'); wrap.className='app-modal'; wrap.innerHTML=`<div class="app-modal__backdrop" data-close></div><section class="app-modal__panel" role="dialog" aria-modal="true" aria-label="${esc(title)}"><button class="app-modal__close" data-close aria-label="Закрыть">×</button><h2>${title}</h2>${body}</section>`;
        document.body.append(wrap); wrap.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>wrap.remove()); return wrap;
    }
    function openAuth() {
        const current=user();
        if(current) return openAccount();
        const m=modal('Создать аккаунт',`<p>Регистрация нужна для сохранения броней на этом устройстве.</p><form class="app-form" data-auth><label>Имя<input name="name" required minlength="2" autocomplete="name"></label><label>Электронная почта<input name="email" type="email" required autocomplete="email"></label><label>Телефон<input name="phone" type="tel" required placeholder="+998 90 000 00 00"></label><label class="app-check"><input type="checkbox" required> Я принимаю условия сервиса</label><button class="btn btn-primary" type="submit">Зарегистрироваться</button></form>`);
        m.querySelector('[data-auth]').onsubmit=e=>{e.preventDefault(); const f=new FormData(e.target); write(STORE.user,{name:f.get('name'),email:f.get('email'),phone:f.get('phone')}); m.remove(); syncAccount(); toast('Аккаунт создан');};
    }
    function openAccount(){const u=user(); const bookings=read(STORE.bookings,[]); const list=bookings.length?bookings.map(b=>`<article class="account-booking"><strong>${esc(b.title)}</strong><span>${esc(b.type)} · ${esc(b.date)}</span><small>${esc(b.destination)}</small><button data-cancel="${b.id}">Отменить бронь</button></article>`).join(''):'<p class="empty-state">У вас пока нет бронирований.</p>'; const m=modal(`Здравствуйте, ${esc(u.name)}`,`<p>${esc(u.email)} · ${esc(u.phone)}</p><div class="account-list">${list}</div><button class="app-text-button" data-logout>Выйти из аккаунта</button>`);m.querySelectorAll('[data-cancel]').forEach(button=>button.onclick=()=>{write(STORE.bookings,read(STORE.bookings,[]).filter(b=>String(b.id)!==button.dataset.cancel));m.remove();toast('Бронирование отменено');openAccount();});m.querySelector('[data-logout]').onclick=()=>{localStorage.removeItem(STORE.user);m.remove();syncAccount();toast('Вы вышли из аккаунта');};}
    function syncAccount(){document.querySelectorAll('[data-account]').forEach(b=>b.textContent=user()?'Мои поездки':'Войти');}
    function addAccountButton(){document.querySelectorAll('.nav-actions').forEach(nav=>{if(nav.querySelector('[data-account]'))return;const b=document.createElement('button');b.className='account-button';b.dataset.account='';b.onclick=openAuth;nav.append(b);});syncAccount();}

    function booking(type,title,destination,price){if(!user()){openAuth();toast('Сначала создайте аккаунт');return;}const today=new Date().toISOString().slice(0,10);const m=modal(type==='Отель'?'Бронирование отеля':'Аренда самоката',`<p><strong>${esc(title)}</strong><br>${esc(destination)} · от ${esc(price)}</p><form class="app-form" data-book><label>Дата<input name="date" type="date" min="${today}" required></label>${type==='Отель'?'<label>Количество ночей<input name="duration" type="number" min="1" max="30" value="2" required></label><label>Гостей<input name="guests" type="number" min="1" max="8" value="2" required></label>':'<label>Количество часов<input name="duration" type="number" min="1" max="12" value="2" required></label>'}<button class="btn btn-primary" type="submit">Подтвердить бронь</button><small>Оплата на месте. Отмена доступна через личный кабинет.</small></form>`);m.querySelector('[data-book]').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const all=read(STORE.bookings,[]);all.unshift({id:Date.now(),type,title,destination,date:f.get('date'),duration:f.get('duration'),status:'confirmed'});write(STORE.bookings,all);m.remove();toast('Бронирование подтверждено');};}

    function linkCityCards(){const map={Ташкент:'tashkent',Самарканд:'samarkand',Бухара:'bukhara',Хива:'khiva',Нукус:'nukus',Андижан:'andijan',Наманган:'namangan',Фергана:'fergana',Джизак:'jizzakh',Карши:'qarshi',Термез:'termez',Гулистан:'gulistan','Навоийская область':'navoi','Ташкентская область':'tashkent_region'};document.querySelectorAll('.city-card').forEach(card=>{const slug=card.dataset.slug||map[card.querySelector('h3')?.textContent.trim()];if(!slug)return;const link=card.querySelector('.mini-btn');if(link)link.href=`/ru/city?city=${slug}`;card.tabIndex=0;card.setAttribute('role','link');card.onclick=e=>{if(!e.target.closest('a'))location.href=`/ru/city?city=${slug}`;};card.onkeydown=e=>{if(e.key==='Enter')location.href=`/ru/city?city=${slug}`;};});}
    function setupHomeHotels(){document.querySelectorAll('#hotels .media-card').forEach(card=>{const title=card.querySelector('h3')?.textContent.trim();const destination=card.querySelector('.details span')?.textContent.trim()||'Узбекистан';if(!title||card.querySelector('[data-home-book]'))return;const button=document.createElement('button');button.className='mini-btn home-book-button';button.dataset.homeBook='';button.textContent='Забронировать';button.onclick=()=>booking('Отель',title,destination,'цена по запросу');card.querySelector('.card-body')?.append(button);});}

    function renderDestination(){
        const root=document.querySelector('[data-destination-page] #destination-root'); if(!root)return;
        const slug=new URLSearchParams(location.search).get('city')||'samarkand'; const d=destinations[slug]||destinations.samarkand; const photo=destinationPhotos[slug];
        document.title=`${d.region} — путеводитель | UzExplore`;
        const places=d.places.map((p,i)=>`<article class="destination-card"><div class="destination-card__photo" style="background-image:linear-gradient(180deg,transparent,rgba(3,20,35,.52)),url('${placePhoto(slug,i)}')"><span>0${i+1}</span><b>${p[0]}</b></div><div class="destination-card__body"><p>${p[2]}</p><a href="https://www.google.com/maps?q=${encodeURIComponent(p[1])}" target="_blank" rel="noopener">📍 ${p[1]} · Открыть карту</a></div></article>`).join('');
        const hotels=hotelNames.map((h,i)=>`<article class="service-card"><div class="service-card__photo" style="background-image:url('${hotelPhoto(slug,i)}')"></div><span>★ ${(4.9-i*.1).toFixed(1)}</span><h3>${i===0?d.name+' '+h:h}</h3><p>${i===0?'Центр города':'Удобное расположение'} · Wi‑Fi · Завтрак${i<2?' · Трансфер':''}</p><strong>от ${(720000-i*110000).toLocaleString('ru-RU')} сум / ночь</strong><button class="btn btn-primary" data-book-hotel data-title="${i===0?d.name+' '+h:h}" data-price="${720000-i*110000} сум">Забронировать</button></article>`).join('');
        root.innerHTML=`<section class="destination-hero" style="background-image:linear-gradient(90deg,rgba(3,21,39,.88),rgba(4,68,78,.48)),url('${photo}')"><div><a class="destination-back" href="/ru#cities">← Все регионы</a><span>${d.region}</span><h1>${d.name}</h1><p>${d.tagline}</p><div class="destination-facts"><span><b>${d.days}</b> рекомендуем</span><span><b>${d.season}</b> лучший сезон</span><span><b>${d.center}</b> центр направления</span></div></div></section><section class="destination-section destination-intro"><div><span class="section-kicker">О регионе</span><h2>Спланируйте поездку</h2></div><p>${d.about}</p></section><section class="destination-section" id="places"><div class="destination-heading"><span class="section-kicker">Главные места</span><h2>Куда поехать</h2><p>Четыре обязательные точки региона. Координаты открываются непосредственно в Google Maps.</p></div><div class="destination-grid">${places}</div></section><section class="destination-section practical-grid"><article><span>🚆</span><h3>Как добраться</h3><p>Из Ташкента — поездом, междугородним автобусом или внутренним рейсом. Для природных маршрутов удобнее трансфер или автомобиль.</p></article><article><span>🍽</span><h3>Что попробовать</h3><p>Региональный плов, самсу, лепёшки, сезонные фрукты и блюда местных чайхан. На рынках удобнее иметь наличные сумы.</p></article><article><span>🧭</span><h3>Перед поездкой</h3><p>Для мечетей выбирайте закрытую одежду, летом берите воду и головной убор, а горные выезды планируйте со связью и гидом.</p></article></section><section class="destination-section destination-section--tint" id="hotels"><div class="destination-heading"><span class="section-kicker">Проживание</span><h2>Где остановиться</h2><p>Варианты для планирования поездки; бронь сохраняется в вашем личном кабинете.</p></div><div class="service-grid">${hotels}</div></section><section class="destination-section" id="mobility"><div class="mobility-panel"><div><span class="section-kicker">Передвижение</span><h2>Транспорт на месте</h2><p>В городе доступны такси и аренда самокатов; для удалённых объектов выбирайте автомобиль с водителем или экскурсию.</p><ul><li>Самокат — от 15 000 сум / час</li><li>Запас хода до 35 км</li><li>Поддержка с 08:00 до 23:00</li></ul></div><button class="btn btn-light" data-book-scooter>Забронировать самокат</button></div></section><section class="destination-section" id="plan"><div class="destination-heading"><span class="section-kicker">Готовый план</span><h2>Маршрут на первый день</h2></div><ol class="day-plan"><li><b>09:00</b> Завтрак и прогулка по центру</li><li><b>10:30</b> ${d.places[0][0]}</li><li><b>13:00</b> Обед с региональной кухней</li><li><b>15:00</b> ${d.places[1][0]}</li><li><b>18:30</b> Закат и ужин</li></ol></section>`;
        root.querySelectorAll('[data-book-hotel]').forEach(b=>b.onclick=()=>booking('Отель',b.dataset.title,d.name,b.dataset.price)); root.querySelector('[data-book-scooter]').onclick=()=>booking('Самокат','UzExplore Scooter',d.name,'15 000 сум / час');
    }

    addAccountButton(); linkCityCards(); setupHomeHotels(); renderDestination();
})();
